# Setup different operating systems
image:
  - Visual Studio 2017
  - macos
  - Ubuntu

# Only build on tags
skip_non_tags: true

# Set SDL2 version
environment:
  SDL2_VERSION: 2.0.10

# Target x86_64
platform: x64

# Install SDL2 (platform specific)
for:
- # Windows setup
  matrix:
    only:
      - image: Visual Studio 2017

  init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

  install:
  - appveyor DownloadFile http://libsdl.org/release/SDL2-devel-%SDL2_VERSION%-VC.zip
  - unzip -o SDL2-devel-%SDL2_VERSION%-VC.zip

  after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - 7z a windows-x86_64.zip build\sdl2_test.exe SDL2-LICENSE.txt LICENSE
  - dir

  artifacts:
  - path: windows-x86_64.zip
    name: Windows-Release

  deploy:
    provider: GitHub
    artifact: Windows-Release
    description: 'Windows Release x86_64'
    auth_token:
      secure: v2mYVuYMnUOmZzKbLhyxjVMH5pQBNJCoXLNhpWfZHPmvhUDhHbgXRKL1T9CWuVyO
    draft: true
    on:
      APPVEYOR_REPO_TAG: true
- # MacOS setup
  matrix:
    only:
      - image: macos
      
  install:
  - brew install sdl2 ninja

  after_build:
  - cd $APPVEYOR_BUILD_FOLDER
  - zip macos-x86_64.zip build/sdl2_test SDL2-LICENSE.txt LICENSE
  - ls

  artifacts:
  - path: macos-x86_64.zip
    name: MacOS-Release

  deploy:
    provider: GitHub
    artifact: MacOS-Release
    description: 'MacOS Release x86_64'
    auth_token:
      secure: v2mYVuYMnUOmZzKbLhyxjVMH5pQBNJCoXLNhpWfZHPmvhUDhHbgXRKL1T9CWuVyO
    draft: true
    on:
      APPVEYOR_REPO_TAG: true
- # Linux setup
  matrix:
    only:
      - image: Ubuntu

  install:
  - sudo apt-get update
  - sudo apt-get install -y libsdl2-dev ninja-build

  after_build:
  - cd $APPVEYOR_BUILD_FOLDER
  - zip linux-x86_64.zip build/sdl2_test SDL2-LICENSE.txt LICENSE
  - ls

  artifacts:
  - path: linux-x86_64.zip
    name: Linux-Release

  deploy:
    provider: GitHub
    artifact: Linux-Release
    description: 'Linux Release x86_64'
    auth_token:
      secure: v2mYVuYMnUOmZzKbLhyxjVMH5pQBNJCoXLNhpWfZHPmvhUDhHbgXRKL1T9CWuVyO
    draft: true
    on:
      APPVEYOR_REPO_TAG: true

# Create build directory and run CMake
before_build:
  - mkdir build
  - cd build
  - cmake -GNinja ..

# Build program
build_script:
  - cmake --build .
