# Setup different operating systems
image:
  - Visual Studio 2017
  - macos
  - Ubuntu

# Set SDL2 version
environment:
  SDL2_VERSION: 2.0.10

# Target x86_64
platform: x64

# Install SDL2 (platform specific)
for:
- # Windows setup
  matrix:
    only:
      - image: Visual Studio 2017

  install:
  - ps: Install-Package sdl2.nuget -RequiredVersion %SDL2_VERSION%
- # MacOS setup
  matrix:
    only:
      - image: macos
      
  install:
  - brew install sdl2
- # Linux setup
  matrix:
    only:
      - image: Ubuntu

  install:
  - sudo apt-get update
  - sudo apt-get install -y libsdl2-dev

# Create build directory and run CMake
before_build:
  - mkdir build
  - cd build
  - cmake ..

# Build program
build_script:
  - cmake --build .

# Deploy build artifacts as releases
#deploy:
#    provider: GitHub
#    artifact: *.exe
#    draft: false
#    prerelease: false
#    on:
#      branch: master                # release from master branch only
#      APPVEYOR_REPO_TAG: true       # deploy on tag push only