# Setup different operating systems
image:
  - Visual Studio 2017
  - macos
  - Ubuntu

# Only build on tags
skip_non_tags: true

# Set SDL2 version
environment:
  SDL2_VERSION: 2.0.10

# Target x86_64
platform: x64

# Install SDL2 (platform specific)
for:
- # Windows setup
  matrix:
    only:
      - image: Visual Studio 2017

  install:
  - appveyor DownloadFile http://libsdl.org/release/SDL2-devel-%SDL2_VERSION%-VC.zip
  - unzip -o SDL2-devel-%SDL2_VERSION%-VC.zip

  after_build:
  - 7z a %APPVEYOR_BUILD_FOLDER%\windows.zip %APPVEYOR_BUILD_FOLDER%\build\Debug\sdl2_test.exe
  - dir

  artifacts:
  - path: windows.zip
    name: Windows-Release
- # MacOS setup
  matrix:
    only:
      - image: macos
      
  install:
  - brew install sdl2

  after_build:
  - zip $APPVEYOR_BUILD_FOLDER/macos.zip $APPVEYOR_BUILD_FOLDER/build/sdl2_test
  - ls

  artifacts:
  - path: macos.zip
    name: MacOS-Release
- # Linux setup
  matrix:
    only:
      - image: Ubuntu

  install:
  - sudo apt-get update
  - sudo apt-get install -y libsdl2-dev

  after_build:
  - zip $APPVEYOR_BUILD_FOLDER/linux.zip $APPVEYOR_BUILD_FOLDER/build/sdl2_test
  - ls

  artifacts:
  - path: linux.zip
    name: Linux-Release

# Create build directory and run CMake
before_build:
  - mkdir build
  - cd build
  - cmake ..

# Build program
build_script:
  - cmake --build .

# Deploy build artifacts as releases
#deploy:
#    provider: GitHub
#    artifact: *.exe
#    draft: false
#    prerelease: false
#    on:
#      branch: master                # release from master branch only
#      APPVEYOR_REPO_TAG: true       # deploy on tag push only